apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  password: root

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
